var annotated_dup =
[
    [ "PtpAnnounceBody", "struct_ptp_announce_body.html", "struct_ptp_announce_body" ],
    [ "PtpBmcaState", "struct_ptp_bmca_state.html", "struct_ptp_bmca_state" ],
    [ "PtpCircBuf", "struct_ptp_circ_buf.html", "struct_ptp_circ_buf" ],
    [ "PtpConfig", "struct_ptp_config.html", "struct_ptp_config" ],
    [ "PtpCoreEvent", "struct_ptp_core_event.html", "struct_ptp_core_event" ],
    [ "PtpCoreState", "struct_ptp_core_state.html", "struct_ptp_core_state" ],
    [ "PtpDelay_RespIdentification", "struct_ptp_delay___resp_identification.html", "struct_ptp_delay___resp_identification" ],
    [ "PtpFlags", "struct_ptp_flags.html", "struct_ptp_flags" ],
    [ "PtpHeader", "struct_ptp_header.html", "struct_ptp_header" ],
    [ "PtpHWClockState", "struct_ptp_h_w_clock_state.html", "struct_ptp_h_w_clock_state" ],
    [ "PtpLogPair", "struct_ptp_log_pair.html", "struct_ptp_log_pair" ],
    [ "PtpMasterMessagingState", "struct_ptp_master_messaging_state.html", "struct_ptp_master_messaging_state" ],
    [ "PtpNetworkState", "struct_ptp_network_state.html", "struct_ptp_network_state" ],
    [ "PtpP2PSlaveInfo", "struct_ptp_p2_p_slave_info.html", "struct_ptp_p2_p_slave_info" ],
    [ "PtpProfile", "struct_ptp_profile.html", "struct_ptp_profile" ],
    [ "PtpProfilePreset", "struct_ptp_profile_preset.html", "struct_ptp_profile_preset" ],
    [ "PtpProfileTlvElement", "struct_ptp_profile_tlv_element.html", "struct_ptp_profile_tlv_element" ],
    [ "PtpServoAuxInput", "struct_ptp_servo_aux_input.html", "struct_ptp_servo_aux_input" ],
    [ "PtpSlaveMessagingState", "struct_ptp_slave_messaging_state.html", "struct_ptp_slave_messaging_state" ],
    [ "PtpStats", "struct_ptp_stats.html", "struct_ptp_stats" ],
    [ "PtpSyncCycleData", "struct_ptp_sync_cycle_data.html", "struct_ptp_sync_cycle_data" ],
    [ "PtpTlvHeader", "struct_ptp_tlv_header.html", "struct_ptp_tlv_header" ],
    [ "PtpTlvPreset", "struct_ptp_tlv_preset.html", "struct_ptp_tlv_preset" ],
    [ "RawPtpMessage", "struct_raw_ptp_message.html", "struct_raw_ptp_message" ],
    [ "TimestampI", "struct_timestamp_i.html", "struct_timestamp_i" ],
    [ "TimestampU", "struct_timestamp_u.html", "struct_timestamp_u" ]
];