on:
  push:
    branches:
      - master
      - doxygen-workflow
permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Generate and Deploy Doxygen Docs
        uses: AgarwalSaurav/ghaction-doxygen-ghpages@release/v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          working-directory: .
          doxyfile-path: Doxyfile
          html-output-folder: docs/html
          branch: gh-pages
          # env_list_file: path/to/env.list  # Uncomment and set if needed (see below)
